// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvtyyxhqgcgfucdpisir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dHl5eGhxZ2NnZnVjZHBpc2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzE1MjcsImV4cCI6MjA2NDMwNzUyN30.dPbrs_xoejEQxn6-PW1wyPYIOCahLO-84zVqw2cgMJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);