// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goaaibvttczyqbsdzsly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvYWFpYnZ0dGN6eXFic2R6c2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzI4MzAsImV4cCI6MjA2NjIwODgzMH0.1dXm98zHeK5WbT2U6i_Szv7w4SgyuSBLAsbPTn2l9tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);